### PR TITLE
adds ico and icon-ref

### LINKED ISSUE #213: Django local server: Not found: favicon.ico
This isn't really an error, but it does throw new developers off to immediately see an error in their logs about no favicon, so we may want to add a favicon.ico route for all the frameworks.

### PR DESCRIPTION
**Pull request by kjaymiller**
fixes #213

### CODE REVIEW

**Comment by pamelafox** [comment]
Can icons be 256x256? I'm used to having to make small ones with pixel editors, but it's very possible times have changed.

**Comment by kjaymiller** [comment]
> Can icons be 256x256? I'm used to having to make small ones with pixel editors, but it's very possible times have changed.

I made an ico file based on the png I did test and it worked but I agree it probably doesn't need to be that large. I can make smaller

**Comment by kjaymiller** [comment]
I opted for about 5 ico files that were for multiple screensizes

**Review by pamelafox — APPROVED** [review]

**Comment by pamelafox** [comment]
tinypng ftw

**Pull request merged**
